name: Laravel

on:
  push:
    branches: [ "*" ]

jobs:
  composer:
    runs-on: ubuntu-latest
    steps: 
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        docker run --rm \
          -u "$(id -u):$(id -g)" \
          -v $(pwd):/var/www/html \
          -w /var/www/html \
          laravelsail/php81-composer:latest \
          composer install --ignore-platform-reqs
        cp .env.example .env
        ./vendor/bin/sail up -d
        ./vendor/bin/sail artisan key:generate
        ./vendor/bin/sail npm install
        ./vendor/bin/sail npm run build
        ./vendor/bin/sail artisan migrate --seed
        ./vendor/bin/sail artisan test
